[2025-02-18T06:40:41.655+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T06:40:41.688+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.load manual__2025-02-18T06:40:28.304506+00:00 [queued]>
[2025-02-18T06:40:41.705+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.load manual__2025-02-18T06:40:28.304506+00:00 [queued]>
[2025-02-18T06:40:41.706+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-18T06:40:41.732+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load> on 2025-02-18 06:40:28.304506+00:00
[2025-02-18T06:40:41.743+0000] {standard_task_runner.py:72} INFO - Started process 3560 to run task
[2025-02-18T06:40:41.752+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'load', 'manual__2025-02-18T06:40:28.304506+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/DAG-fraud.py', '--cfg-path', '/tmp/tmp1rzqdrns']
[2025-02-18T06:40:41.754+0000] {standard_task_runner.py:105} INFO - Job 136: Subtask load
[2025-02-18T06:40:41.840+0000] {task_command.py:467} INFO - Running <TaskInstance: ml_pipeline.load manual__2025-02-18T06:40:28.304506+00:00 [running]> on host 8538735272b1
[2025-02-18T06:40:42.066+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='group1' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-02-18T06:40:28.304506+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-18T06:40:28.304506+00:00'
[2025-02-18T06:40:42.068+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-18T06:40:42.554+0000] {base.py:84} INFO - Retrieving connection 'postgres_***'
[2025-02-18T06:41:01.410+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-18T06:41:01.622+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-18T06:41:01.628+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=ml_pipeline, task_id=load, run_id=manual__2025-02-18T06:40:28.304506+00:00, execution_date=20250218T064028, start_date=20250218T064041, end_date=20250218T064101
[2025-02-18T06:41:01.777+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T06:41:01.781+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-02-18T06:41:01.923+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-18T06:41:01.930+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
