[2025-02-16T08:29:15.870+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pipeline_group1.extract_data manual__2025-02-16T08:29:12.889128+00:00 [queued]>
[2025-02-16T08:29:15.887+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pipeline_group1.extract_data manual__2025-02-16T08:29:12.889128+00:00 [queued]>
[2025-02-16T08:29:15.888+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-02-16T08:29:15.889+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-02-16T08:29:15.889+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-02-16T08:29:15.911+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): extract_data> on 2025-02-16 08:29:12.889128+00:00
[2025-02-16T08:29:15.930+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pipeline_group1', 'extract_data', 'manual__2025-02-16T08:29:12.889128+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_inka_DAG.py', '--cfg-path', '/tmp/tmpnr1egla5', '--error-file', '/tmp/tmp16p6r1a4']
[2025-02-16T08:29:15.928+0000] {standard_task_runner.py:52} INFO - Started process 575 to run task
[2025-02-16T08:29:15.933+0000] {standard_task_runner.py:80} INFO - Job 9: Subtask extract_data
[2025-02-16T08:29:16.179+0000] {task_command.py:371} INFO - Running <TaskInstance: pipeline_group1.extract_data manual__2025-02-16T08:29:12.889128+00:00 [running]> on host 8d7c06d84acb
[2025-02-16T08:29:16.345+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pipeline_group1
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2025-02-16T08:29:12.889128+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-16T08:29:12.889128+00:00
[2025-02-16T08:29:16.406+0000] {base.py:68} INFO - Using connection ID 'postgres_***' for task execution.
[2025-02-16T08:30:09.783+0000] {local_task_job.py:156} INFO - Task exited with return code Negsignal.SIGKILL
[2025-02-16T08:30:13.711+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=pipeline_group1, task_id=extract_data, execution_date=20250216T082912, start_date=20250216T082915, end_date=20250216T083013
[2025-02-16T08:30:14.330+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
